name: Daily Birthday Check

on:
  schedule:
    # Run at midnight (00:00) every day
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-birthdays:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run birthday check
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER_EMAIL: ${{ secrets.SMTP_USERNAME }} # Changed from SMTP_USERNAME to SENDER_EMAIL
          SENDER_PASSWORD: ${{ secrets.SMTP_PASSWORD }} # Changed from SMTP_PASSWORD to SENDER_PASSWORD
          # DATABASE_PATH, EMAIL_SUBJECT, EMAIL_TEMPLATE_PATH will use defaults from config.py
          # or you can add them as secrets if they need to be different in Actions
        run: python src/main.py
